using FluentAssertions;
using MyraUIGenerator;
using MyraUIGenerator.Tests.Helpers;
using System.Collections.Generic;
using Xunit;

namespace MyraUIGenerator.Tests.Unit;

public class CodeGenerationTests
{
    [Fact]
    public void GenerateUIClass_BasicClassGeneration()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "TestButton", Type = "TextButton", PropertyName = "TestButton" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("namespace TestNamespace");
        result.Should().Contain("public partial class TestUI");
        result.Should().Contain("public TextButton TestButton { get; private set; }");
        result.Should().Contain("public void Initialize(Widget root)");
        result.Should().Contain("TestButton = root.FindChildById(\"TestButton\") as TextButton;");
    }

    [Fact]
    public void GenerateUIClass_MultipleWidgets()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Label1", Type = "Label", PropertyName = "Label1" },
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" },
            new MyraUIGenerator.WidgetInfo { Id = "Button2", Type = "Button", PropertyName = "Button2" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("public Label Label1 { get; private set; }");
        result.Should().Contain("public TextButton Button1 { get; private set; }");
        result.Should().Contain("public Button Button2 { get; private set; }");
        result.Should().Contain("Label1 = root.FindChildById(\"Label1\") as Label;");
        result.Should().Contain("Button1 = root.FindChildById(\"Button1\") as TextButton;");
        result.Should().Contain("Button2 = root.FindChildById(\"Button2\") as Button;");
    }

    [Fact]
    public void GenerateUIClass_CustomNamespace()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "Custom.Namespace.UI");

        // Assert
        result.Should().Contain("namespace Custom.Namespace.UI");
        result.Should().NotContain("namespace GeneratedUI");
    }

    [Fact]
    public void GenerateUIClass_PartialClassKeyword()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("public partial class");
    }

    [Fact]
    public void GenerateUIClass_XMLDocumentation()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("TestScreen", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("/// <summary>");
        result.Should().Contain("Auto-generated UI accessor for TestScreen.xml");
        result.Should().Contain("This file is automatically generated by MyraUIGenerator - do not edit manually.");
    }

    [Fact]
    public void GenerateUIClass_UsingStatements()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("using Myra.Graphics2D.UI;");
        result.Should().Contain("using System;");
    }

    [Fact]
    public void GenerateUIClass_PropertyTypes()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Label1", Type = "Label", PropertyName = "Label1" },
            new MyraUIGenerator.WidgetInfo { Id = "Custom1", Type = "CustomWidget", PropertyName = "Custom1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("public Label Label1");
        result.Should().Contain("public CustomWidget Custom1");
    }

    [Fact]
    public void GenerateUIClass_PropertyNames()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Widget_1", Type = "Label", PropertyName = "Widget_1" },
            new MyraUIGenerator.WidgetInfo { Id = "MyWidget123", Type = "Label", PropertyName = "MyWidget123" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("public Label Widget_1");
        result.Should().Contain("public Label MyWidget123");
    }

    [Fact]
    public void GenerateUIClass_InitializeMethodSignature()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        result.Should().Contain("public void Initialize(Widget root)");
    }

    [Fact]
    public void GenerateUIClass_CodeFormatting()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result = generator.GenerateUIClass("Test", widgets, "TestNamespace");

        // Assert
        var lines = result.Split('\n');
        lines.Should().NotBeEmpty();
        // Check that properties are indented
        lines.Should().Contain(l => l.Contains("    public TextButton Button1"));
        // Check that Initialize method body is indented
        lines.Should().Contain(l => l.Contains("        Button1 = root.FindChildById"));
    }

    [Fact]
    public void GenerateUIClass_ClassNameMatchesFileName()
    {
        // Arrange
        var generator = new MyraUIGenerator();
        var widgets = new List<MyraUIGenerator.WidgetInfo>
        {
            new MyraUIGenerator.WidgetInfo { Id = "Button1", Type = "TextButton", PropertyName = "Button1" }
        };

        // Act
        var result1 = generator.GenerateUIClass("TitleScreen", widgets, "TestNamespace");
        var result2 = generator.GenerateUIClass("MainMenu", widgets, "TestNamespace");

        // Assert
        result1.Should().Contain("public partial class TitleScreenUI");
        result2.Should().Contain("public partial class MainMenuUI");
    }
}

